
-- Tablas para sincronizacion --

-- DATOS_ALTEM
CREATE TABLE `DATOS_ALTEM` (
   `ID_ESTUDIANTE` VARCHAR(36) NOT NULL,
   `PGA_ACOMULADO` VARCHAR(45) DEFAULT NULL,
   `PROMEDIO_PERIODO` VARCHAR(45) DEFAULT NULL,
   `PERIODO` VARCHAR(24) NOT NULL,
   `NRC` VARCHAR(20) NOT NULL,
   `MATERIA` VARCHAR(16) NOT NULL,
   `CURSO` VARCHAR(20) NOT NULL,
   `ASIGNATURA` VARCHAR(120),
   `SESION` VARCHAR(12) NOT NULL,
   `Lunes` VARCHAR(35),
   `Martes` VARCHAR(35),
   `Miercoles` VARCHAR(35),
   `Jueves` VARCHAR(35),
   `Viernes` VARCHAR(35),
   `Sabado` VARCHAR(35),
   `Domingo` VARCHAR(35),
   `TIPO` VARCHAR(12),
   `Hrs/Sem` INT(11) DEFAULT NULL,
   `COD_ESTATUS` VARCHAR(8),
   `COD_COMPONENTE` VARCHAR(40),
   `TIPO_DE_CAPTURA` VARCHAR(8),
   `NOTA_PARCIAL` VARCHAR(24),
   `ID_DOCENTE` VARCHAR(36),
   `APELLIDOS_DOCENTE` VARCHAR(240),
   `NOMBRES_DOCENTE` VARCHAR(481),
   `NRO_COMPONENTES` VARCHAR(45) DEFAULT NULL,
   `FECHA` VARCHAR(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1

-- DATOS_ESTUDIANTES_ALTEM
CREATE TABLE `DATOS_ESTUDIANTES_ALTEM` (
   `ID` VARCHAR(36) NOT NULL,
   `NOMBRES` VARCHAR(484),
   `APELLIDOS` VARCHAR(45),
   `TIPO_DOC` VARCHAR(45),
   `NO_DOC` VARCHAR(45),
   `SEXO` VARCHAR(45),
   `ESTADO_CIVIL` VARCHAR(45),
   `FECHA_NACIMENTO` DATE,
   `CIUDAD1` TEXT,
   `DIRECCION1` TEXT,
   `TELEFONO1` VARCHAR(45),
   `CIUDAD2` TEXT,
   `DIRECCION2` TEXT,
   `TELEFONO2` VARCHAR(45),
   `EMAIL` VARCHAR(45),
   `PROGRAMA` VARCHAR(45),
   `COD_ESTADO` VARCHAR(8),
   `ESTADO` VARCHAR(45),
   `COD_TIPO` VARCHAR(4),
   `TIPO_ESTUDIANTE` VARCHAR(45),
   `SITUACION` VARCHAR(45),
   `PGA_ACOMULADO` VARCHAR(45),
   `ESTRATO` VARCHAR(45),
   `BECAS` VARCHAR(45),
   `CERES` VARCHAR(45),
   `NOMBRE_ACUDIENTE` LONGTEXT,
   `DIRECCION_ACUDIENTE` VARCHAR(45),
   `TELEFONO_ACUDIENTE` VARCHAR(76),
   `NIVEL_ACT` VARCHAR(45),
   `PERIODO_INGRESO` VARCHAR(45)
) ENGINE=InnoDB DEFAULT CHARSET=latin1


-- vistas que consumen las tablas sincronizadas, usadas por ALTEM --

-- estudiantes_view
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `estudiantes_view` AS
    SELECT 
        `DATOS_ESTUDIANTES_ALTEM`.`ID` AS `ID`,
        `DATOS_ESTUDIANTES_ALTEM`.`NOMBRES` AS `NOMBRES`,
        `DATOS_ESTUDIANTES_ALTEM`.`APELLIDOS` AS `APELLIDOS`,
        `DATOS_ESTUDIANTES_ALTEM`.`TIPO_DOC` AS `TIPO_DOC`,
        `DATOS_ESTUDIANTES_ALTEM`.`NO_DOC` AS `NO_DOC`,
        `DATOS_ESTUDIANTES_ALTEM`.`SEXO` AS `SEXO`,
        `DATOS_ESTUDIANTES_ALTEM`.`ESTADO_CIVIL` AS `ESTADO_CIVIL`,
        `DATOS_ESTUDIANTES_ALTEM`.`FECHA_NACIMENTO` AS `FECHA_NACIMENTO`,
        `DATOS_ESTUDIANTES_ALTEM`.`CIUDAD1` AS `CIUDAD1`,
        `DATOS_ESTUDIANTES_ALTEM`.`DIRECCION1` AS `DIRECCION1`,
        `DATOS_ESTUDIANTES_ALTEM`.`TELEFONO1` AS `TELEFONO1`,
        `DATOS_ESTUDIANTES_ALTEM`.`CIUDAD2` AS `CIUDAD2`,
        `DATOS_ESTUDIANTES_ALTEM`.`DIRECCION2` AS `DIRECCION2`,
        `DATOS_ESTUDIANTES_ALTEM`.`TELEFONO2` AS `TELEFONO2`,
        `DATOS_ESTUDIANTES_ALTEM`.`EMAIL` AS `EMAIL`,
        `DATOS_ESTUDIANTES_ALTEM`.`PROGRAMA` AS `PROGRAMA`,
        `DATOS_ESTUDIANTES_ALTEM`.`COD_ESTADO` AS `COD_ESTADO`,
        `DATOS_ESTUDIANTES_ALTEM`.`ESTADO` AS `ESTADO`,
        `DATOS_ESTUDIANTES_ALTEM`.`COD_TIPO` AS `COD_TIPO`,
        `DATOS_ESTUDIANTES_ALTEM`.`TIPO_ESTUDIANTE` AS `TIPO_ESTUDIANTE`,
        `DATOS_ESTUDIANTES_ALTEM`.`SITUACION` AS `SITUACION`,
        `DATOS_ESTUDIANTES_ALTEM`.`ESTRATO` AS `ESTRATO`,
        `DATOS_ESTUDIANTES_ALTEM`.`BECAS` AS `BECAS`,
        `DATOS_ESTUDIANTES_ALTEM`.`CERES` AS `CERES`,
        `DATOS_ESTUDIANTES_ALTEM`.`NOMBRE_ACUDIENTE` AS `NOMBRE_ACUDIENTE`,
        `DATOS_ESTUDIANTES_ALTEM`.`DIRECCION_ACUDIENTE` AS `DIRECCION_ACUDIENTE`,
        `DATOS_ESTUDIANTES_ALTEM`.`TELEFONO_ACUDIENTE` AS `TELEFONO_ACUDIENTE`,
        `DATOS_ESTUDIANTES_ALTEM`.`NIVEL_ACT` AS `NIVEL_ACT`,
        `DATOS_ESTUDIANTES_ALTEM`.`PERIODO_INGRESO` AS `PERIODO_INGRESO`,
        `DATOS_ESTUDIANTES_ALTEM`.`PGA_ACOMULADO` AS `PGA_ACUMULADO`
    FROM
        `DATOS_ESTUDIANTES_ALTEM`

-- datos_academicos_view
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `datos_academicos_view` AS
    SELECT 
        `DATOS_ALTEM`.`ID_ESTUDIANTE` AS `ID`,
        `DATOS_ALTEM`.`FECHA` AS `FECHA`,
        `DATOS_ALTEM`.`NRO_COMPONENTES` AS `NRO_COMPONENTES`,
        `DATOS_ALTEM`.`NOMBRES_DOCENTE` AS `NOMBRES_DOCENTE`,
        `DATOS_ALTEM`.`APELLIDOS_DOCENTE` AS `APELLIDOS_DOCENTE`,
        `DATOS_ALTEM`.`ID_DOCENTE` AS `ID_DOCENTE`,
        `DATOS_ALTEM`.`NOTA_PARCIAL` AS `NOTA_PARCIAL`,
        `DATOS_ALTEM`.`TIPO_DE_CAPTURA` AS `TIPO_DE_CAPTURA`,
        `DATOS_ALTEM`.`COD_COMPONENTE` AS `COD_COMPONENTE`,
        `DATOS_ALTEM`.`COD_ESTATUS` AS `COD_ESTATUS`,
        `DATOS_ALTEM`.`Hrs/Sem` AS `Hrs_Sem`,
        `DATOS_ALTEM`.`TIPO` AS `TIPO`,
        `DATOS_ALTEM`.`Domingo` AS `Domingo`,
        `DATOS_ALTEM`.`Sabado` AS `Sabado`,
        `DATOS_ALTEM`.`Viernes` AS `Viernes`,
        `DATOS_ALTEM`.`Jueves` AS `Jueves`,
        `DATOS_ALTEM`.`Miercoles` AS `Miercoles`,
        `DATOS_ALTEM`.`Martes` AS `Martes`,
        `DATOS_ALTEM`.`Lunes` AS `Lunes`,
        `DATOS_ALTEM`.`SESION` AS `SESION`,
        `DATOS_ALTEM`.`ASIGNATURA` AS `ASIGNATURA`,
        `DATOS_ALTEM`.`CURSO` AS `CURSO`,
        `DATOS_ALTEM`.`MATERIA` AS `MATERIA`,
        `DATOS_ALTEM`.`NRC` AS `NRC`,
        `DATOS_ALTEM`.`PERIODO` AS `PERIODO`,
        `DATOS_ALTEM`.`PROMEDIO_PERIODO` AS `PROMEDIO_PERIODO`,
        `DATOS_ALTEM`.`PGA_ACOMULADO` AS `PGA_ACOMULADO`
    FROM
        `DATOS_ALTEM`
    GROUP BY `DATOS_ALTEM`.`ID_ESTUDIANTE`
    
    -- configuración sql_mode
    
    SET @@sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
